/* Service Worker generated by Workbox */

declare const self: ServiceWorkerGlobalScope & { __WB_MANIFEST: Array<any> };

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Precache assets generated by workbox-build
precacheAndRoute(self.__WB_MANIFEST || []);

// Cache static assets (images, scripts, styles, html) with Cache First
registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style' || request.destination === 'image' || request.destination === 'document',
  new CacheFirst({
    cacheName: 'static-assets',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 30 * 24 * 60 * 60 }),
    ],
  })
);

// Cache audio files with Stale While Revalidate
registerRoute(
  ({ url }) => url.pathname.endsWith('.mp3') || url.pathname.endsWith('.ogg'),
  new StaleWhileRevalidate({
    cacheName: 'audio-assets',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 365 * 24 * 60 * 60 }),
    ],
  })
);

// Take control of the page as soon as the service worker activates.
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Skip waiting on new service worker installation to update caches immediately.
self.addEventListener('install', (event) => {
  self.skipWaiting();
});
